// Generated by gencpp from file hectorquad/coordinateResponse.msg
// DO NOT EDIT!


#ifndef HECTORQUAD_MESSAGE_COORDINATERESPONSE_H
#define HECTORQUAD_MESSAGE_COORDINATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hectorquad
{
template <class ContainerAllocator>
struct coordinateResponse_
{
  typedef coordinateResponse_<ContainerAllocator> Type;

  coordinateResponse_()
    : s()  {
    }
  coordinateResponse_(const ContainerAllocator& _alloc)
    : s(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _s_type;
  _s_type s;





  typedef boost::shared_ptr< ::hectorquad::coordinateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hectorquad::coordinateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct coordinateResponse_

typedef ::hectorquad::coordinateResponse_<std::allocator<void> > coordinateResponse;

typedef boost::shared_ptr< ::hectorquad::coordinateResponse > coordinateResponsePtr;
typedef boost::shared_ptr< ::hectorquad::coordinateResponse const> coordinateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hectorquad::coordinateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hectorquad::coordinateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hectorquad

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hectorquad::coordinateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hectorquad::coordinateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hectorquad::coordinateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hectorquad::coordinateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hectorquad::coordinateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hectorquad::coordinateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hectorquad::coordinateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81af3411577d82a6786258523fc891ce";
  }

  static const char* value(const ::hectorquad::coordinateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81af3411577d82a6ULL;
  static const uint64_t static_value2 = 0x786258523fc891ceULL;
};

template<class ContainerAllocator>
struct DataType< ::hectorquad::coordinateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hectorquad/coordinateResponse";
  }

  static const char* value(const ::hectorquad::coordinateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hectorquad::coordinateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string s\n\
";
  }

  static const char* value(const ::hectorquad::coordinateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hectorquad::coordinateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coordinateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hectorquad::coordinateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hectorquad::coordinateResponse_<ContainerAllocator>& v)
  {
    s << indent << "s: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HECTORQUAD_MESSAGE_COORDINATERESPONSE_H
